import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import AppHeader from "@/components/AppHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <style>
        @import
        url('https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap');
      </style>
      <body className={inter.className}>
        <AppHeader />
        {children}
        </body>
    </html>
  );
}
