import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.scss";
import AppHeader from "@/src/components/AppHeader";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <style>
        @import
        url('https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap');
      </style>
      <link
        href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css"
        rel="stylesheet"
      />
      <body className={inter.className}>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
